const actionTypes = {
    REGISTRATION_REQUEST_ERROR: 'REGISTRATION_REQUEST_ERROR',
    REGISTRATION_REQUEST_SUCCESS: 'REGISTRATION_REQUEST_SUCCESS',
    SEND_REGISTRATION_REQUEST: 'SEND_REGISTRATION_REQUEST',
};

export default actionTypes;
