const actionTypes = {
    REQUEST_LOAD_FORUM_DATA: 'REQUEST_LOAD_FORUM_DATA',
    REQUEST_SET_FORUM_DATA_ERROR: 'REQUEST_SET_FORUM_DATA_ERROR',
    REQUEST_SET_FORUM_DATA_SUCCESS: 'REQUEST_SET_FORUM_DATA_SUCCESS',
};

export default actionTypes;
