const actionTypes = {
    ADD_POST_TO_TIMELINE: 'ADD_POST_TO_TIMELINE',
    CLEAR_STATUS_FIELD: 'CLEAR_STATUS_FIELD',
    FETCH_PROFILE_DATA_FAILURE: 'FETCH_PROFILE_DATA_FAILURE',
    FETCH_PROFILE_DATA_SUCCESS: 'PROFILE_DATA_SUCCESS',
    FETCH_PROFILE_REQUEST: 'FETCH_PROFILE_REQUEST',
    TOGGLE_MODAL: 'TOGGLE MODAL',
    UPDATE_STATUS: 'UPDATE_STATUS',
};

export default actionTypes;
