const actionTypes = {
    ADD_COMMENT_TO_POST: 'ADD_COMMENT_TO_POST',
    ADD_POST_TO_TIMELINE: 'ADD_POST_TO_TIMELINE',
    CLEAR_STATUS_FIELD: 'CLEAR_STATUS_FIELD',
    REQUEST_LOAD_ONLINE_FRIENDS_DATA: 'REQUEST_LOAD_ONLINE_FRIENDS_DATA',
    REQUEST_LOAD_TIMELINE_DATA: 'REQUEST_LOAD_TIMELINE_DATA',
    REQUEST_SET_ONLINE_FRIENDS_DATA: 'REQUEST_SET_ONLINE_FRIENDS_DATA',
    REQUEST_SET_ONLINE_FRIENDS_ERROR: 'REQUEST_SET_ONLINE_FRIENDS_ERROR',
    REQUEST_SET_TIMELINE_DATA_SUCCESS: 'REQUEST_SET_TIMELINE_DATA_SUCCESS',
    REQUEST_SET_TIMELINE_ERROR: 'REQUEST_SET_TIMELINE_ERROR',
    TOGGLE_COMMENT_BUTTON_CLICKED: 'TOGGLE_COMMENT_BUTTON_CLICKED',
    TOGGLE_FAV_BUTTON_CLICKED: 'TOGGLE_FAV_BUTTON_CLICKED',
    TOGGLE_LIKE_BUTTON_CLICKED: 'TOGGLE_LIKE_BUTTON_CLICKED',
    UPDATE_STATUS: 'UPDATE_STATUS',
};

export default actionTypes;
